#!/bin/sh
# Made from i-MSCP - internet Multi Server Control Panel
# Copyright (C) 2010-2015 by Laurent Declercq <l.declercq@nuxwin.com> GNU GPL v2
# Rewrited by Vitaliy Zhukov <dragonzx@soclan.ru> for use with RadioCMS
set -e

cd ../..

if [ ! -f "index.php" ]; then
	echo "You must run this script from the i18n/tools directory!"
	exit 1
fi

# Purge any old language file
rm -fR locale/l10n/*

for i in `find locale/po-source -name '*.po' | sed -r 's/.*\/(.*)/\1/'`; do
	echo "Compiling machine object file: ${i}"
	LOCALE=`echo ${i} | cut -d '.' -f 1`
	DESTDIR="locale/l10n/${LOCALE}/LC_MESSAGES"
	mkdir -p ${DESTDIR}
	msgfmt --strict --no-hash -o ${DESTDIR}/${LOCALE}.mo locale/po-source/${i}
done
