#!/bin/sh
# Made from i-MSCP - internet Multi Server Control Panel
# Copyright (C) 2010-2015 by Laurent Declercq <l.declercq@nuxwin.com> GNU GPL v2
# Rewrited by Vitaliy Zhukov <dragonzx@soclan.ru> for use with RadioCMS

set -e

i18N_DIR=$(readlink -f ../)

if [ ! -d ${i18N_DIR}/po-source ]; then
	echo "You must run this script from the i18n/tools directory."
	exit 1
fi

GUI_DIR=$(readlink -f ../../)

# PHP files
find ${GUI_DIR} -type f -name '*.php' -print > php.lst
/usr/bin/xgettext --copyright-holder='RadioCMS Team - All rights reserved' --package-name='RadioCMS' \
--package-version="<version>" --msgid-bugs-address='i18n@soclan.ru' --language=PHP --keyword='tr' --keyword='ntr:1,2' \
--from-code=utf-8 --files-from=php.lst --no-location --sort-output --output=${i18N_DIR}/iMSCP.pot
rm -f php.lst

# JS files
find ${GUI_DIR} -type f -name '*.js' -print > js.lst
/usr/bin/xgettext --language=Javascript --omit-header --keyword='label' --files-from=js.lst --no-location --sort-output \
--join-existing --output=${i18N_DIR}/RadioCMS.pot
rm -f xml.lst
